# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Group', verbose_name='parent group')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=50)),
                ('empno', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('role', models.ManyToManyField(to='sysmgr.Role')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.ManyToManyField(to='sysmgr.Role'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='sysmgr.User'),
        ),
    ]
