# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=50)),
                ('empno', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
