# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-02 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=6)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=50)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Group', verbose_name='parent group')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=6)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=50)),
                ('addr', models.CharField(blank=True, max_length=150, null=True)),
                ('addr_param', models.CharField(blank=True, max_length=50)),
                ('i_class', models.CharField(blank=True, max_length=100, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('menu_type', models.CharField(choices=[('dashboard', 'dashboard'), ('console', 'console')], default='console', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Menu', verbose_name='parent menu')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=6)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=50)),
                ('cloud_type', models.CharField(choices=[('private', 'private'), ('private', 'public')], default='private', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=6)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ManyToManyField(to='sysmgr.Menu')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleRegionPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Region')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmgr.Role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=50)),
                ('empno', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('role', models.ManyToManyField(to='sysmgr.Role')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.ManyToManyField(to='sysmgr.Role'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='sysmgr.User'),
        ),
    ]
