# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_overseas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='sysmgr.Menu'),
        ),
    ]
